### ISSUE TITLE
Admin view not working

### ISSUE THREAD

**Issue by fullmvc** [vasadibt/yii2-cron#1]
When you want to load the index view, error reise because common\helpers\Html class not found.
The views/cron-job-run/index.php using the same helper, although the console/components/Console Class.
The commands/CronController using the common/helpers/ArrayHelper, console/components/Console Classes.
You using vasadibt\grid\SerialColumn in the gridview but it's not found.

I hope i helped you out! ;)

**Comment by vasadibt** [comment]
Fixed on version 1.0.1
