### ISSUE TITLE
migration

### ISSUE THREAD

**Issue by Djagannath** [vasadibt/yii2-cron#7]
'active' => $this->boolean()->notNull()->defaultValue(1),
> create table {{%cron_job}} ...Exception: SQLSTATE[42804]: Datatype mismatch: 7 ERROR:  column "active" is of type boolean but default expression is of type integer

**Comment by fullmvc** [comment]
Whitch database system and version do you use (mysql, mariadb, postgresql, mongodb mssql, etc.)?

**Comment by Djagannath** [comment]
PostgreSQL 9.6.17 With defaultValue(true) works well

**Comment by vasadibt** [comment]
Fixed in #8 commit
